[tool.poetry]
name = "opendeliverybot"
version = "0.1.10"
description = "ðŸ¤–ðŸ“¦ Deliver anything, anywere! powered by MineFlayer."
authors = ["Silke pilon <silkepilon2009@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
javascript = "^1!1.0.3"
click = "^8.1.7"
rich = "^13.5.2"
tqdm = "^4.66.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
